coveralls: true
language: julia
julia:
  - nightly
  - 1.0.5
  - 1
os:
  - linux
  - osx
  - window

# blocklist
branches:
  except:
  - development

# safelist
branches:
  only:
  - master
  - staging